<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUdr7xjl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUdr7xjl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUdr7xjl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUdr7xjl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUdr7xjl\appProdProjectContainer(array(
    'container.build_hash' => 'Udr7xjl',
    'container.build_id' => '6272a43b',
    'container.build_time' => 1535910683,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUdr7xjl');
